### ISSUE TITLE
Test_HICO_res101_x2_2_0064999_FPN_hico.pkl

### ISSUE THREAD

**Issue by WXLL579** [zhihou7/VCL_Pytorch#1]
hello! thanks for your excellent work! I have a problem when running the code:
In testing, 
Default ===========
Traceback (most recent call last):
  File "tools/Test_ResNet_HICO.py", line 115, in <module>
    std=[0.229, 0.224, 0.225])]),
  File "tools/Test_ResNet_HICO.py", line 63, in __init__
    stride=stride, test_type=args.test_type, model_name=args.model)
  File "D:\run_paper\VCL_Pytorch-master\tools\..\lib\models\test_HICO.py", line 231, in obtain_test_dataset1
    Test_RCNN = obtain_obj_boxes(test_type)
  File "D:\run_paper\VCL_Pytorch-master\tools\..\lib\models\test_HICO.py", line 390, in obtain_obj_boxes
    Test_RCNN = pickle.load(open(cfg.DATA_DIR + '/' + 'Test_HICO_res101_x2_2_0064999_FPN_hico.pkl', "rb"),
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\run_paper\\VCL_Pytorch-master\\Data/Test_HICO_res101_x2_2_0064999_FPN_hico.pkl'

What is 'Test_HICO_res101_x2_2_0064999_FPN_hico.pkl'? Where can it be downloaded?       thanks！

**Comment by zhihou7** [comment]
I am sorry for the issue. I did not implement VCL based pytorch successfully. This repository can not converge. See this issues:https://discuss.pytorch.org/t/the-difference-between-tf-image-crop-and-resize-vs-torchvision-ops-roi-align/106825.

To make the code converge, I have to add some additional strategies e.g. focal loss, pos_weight. However, in the tensorflow version, those strategies are not required.

However, I implement VCL and ATL based on one-stage HOI detection method in https://github.com/zhihou7/HOI-CL-OneStage, which is a pytorch-based repository. It is based on detectron2.

Test_HICO_res101_x2_2_0064999_FPN_hico.pkl is vcl boxes (named as Test_HICO_res101_3x_FPN_hico.pkl in my other repositories). You can download from https://drive.google.com/file/d/1QI1kcZJqI-ym6AGQ2swwp4CKb39uLf-4/view?usp=sharing.

You can also download ground truth boxes from https://drive.google.com/file/d/15UXbsoverISJ9wNO-84uI4kQEbRjyRa8/view.  


Regards

**Comment by WXLL579** [comment]
thanks
